# Generated by Django 3.1.7 on 2021-03-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
