# Generated by Django 3.1.7 on 2021-03-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0003_motorista_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='zona',
            field=models.CharField(default='Zona Santiago', max_length=50),
        ),
    ]
